version: "3.9"  # optional since v1.27.0
services:
  database:
    container_name: "tokenify-db-postgres"
    image: postgres:14.5-alpine3.16
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tokenify-db-postgres
    restart: "always"
    healthcheck:
      test: "pg_isready --username=postgres"
      interval: 3s
      timeout: 2s
      retries: 10
  flyway:
     container_name: migration
     image: flyway/flyway:9.3.1
     environment:
      - FLYWAY_USER=postgres
      - FLYWAY_PASSWORD=postgres
      - FLYWAY_URL=jdbc:postgresql://tokenify-db-postgres:5432/tokenify-db-postgres
      - FLYWAY_VALIDATE_MIGRATION_NAMING=true
     command: -locations=filesystem:/flyway/sql -connectRetries=60 migrate
     volumes:
      - ./sql:/flyway/sql
     depends_on:
        database:
            condition: service_healthy
networks:
  bridge:
    external: true

